### ISSUE TITLE
Magic storage freezes character and shows vanity

### ISSUE THREAD

**Issue by TheRealRitzer** [blushiemagic/MagicStorage#101]
title, it only happens if i have my storage heart connected to my storage blocks, if i have it anywhere else theres no issue, i tried removing the storage blocks, but i cant do it, because when i deactivate them it doesnt let me mine them, im using tmod 64 bit if that matters, heres the error it game me.

[10:59:35] [1/WARN] [tML]: Silently Caught Exception:
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at MagicStorage.Sorting.SortClassList.FrameImportantTile(Item item) in MagicStorage\Sorting\DefaultSorting.cs:line 275
   at MagicStorage.Sorting.SortClassList.Compare(Item item1, Item item2) in MagicStorage\Sorting\DefaultSorting.cs:line 32
   at MagicStorage.Sorting.BTreeNode`1.InsertIntoBranch(T item, T& pushItem, BTreeNode`1& pushNode) in MagicStorage\Sorting\BTree.cs:line 145
   at MagicStorage.Sorting.BTreeNode`1.Insert(T item, T& pushItem, BTreeNode`1& pushBranch) in MagicStorage\Sorting\BTree.cs:line 78
   at MagicStorage.Sorting.BTree`1.Insert(T item) in MagicStorage\Sorting\BTree.cs:line 24
   at MagicStorage.Sorting.ItemSorter.SortAndFilter(IEnumerable`1 items, SortMode sortMode, FilterMode filterMode, String modFilter, String nameFilter) in MagicStorage\Sorting\ItemSorter.cs:line 60
   at MagicStorage.StorageGUI.RefreshItems() in MagicStorage\StorageGUI.cs:line 358
   at MagicStorage.Components.StorageAccess.NewRightClick(Int32 i, Int32 j) in MagicStorage\Components\StorageAccess.cs:line 108
   at MagicStorage.Components.StorageHeart.NewRightClick(Int32 i, Int32 j) in MagicStorage\Components\StorageHeart.cs:line 61
   at Terraria.ModLoader.TileLoader.RightClick(Int32 i, Int32 j)
   at Terraria.Player.TileInteractionsUse(Int32 myX, Int32 myY)
   at Terraria.Player.TileInteractionsCheck(Int32 myX, Int32 myY)
   at DMD<Terraria.Player::Update>(Player , Int32 )
   at Terraria.Main.DoUpdate(GameTime gameTime)
   at Terraria.Main.Update(GameTime gameTime)
   at Microsoft.Xna.Framework.Game.Tick()
   at Microsoft.Xna.Framework.SDL2_FNAPlatform.RunLoop(Game game)
   at Microsoft.Xna.Framework.Game.Run()
   at Terraria.Program.LaunchGame_()
   at Terraria.Program.LaunchGame(String[] args, Boolean monoArgs)
   at Terraria.FNALaunch.Main(String[] args)

**Comment by absoluteAquarian** [comment]
The following message has been copy/pasted to all issues older than 3 months.

In order to clean up how the project looks, I'll be closing all old issues.  If you believe that this issue is still relevant, please make a new issue that references this issue in its message.
