### ISSUE TITLE
Error on opening wireless handheld storage access

### ISSUE THREAD

**Issue by Redcom1988** [blushiemagic/MagicStorage#103]
> > [13:39:51] [1/WARN] [tML]: Silently Caught Exception: 
> > System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
> >    at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
> >    at MagicStorage.Components.StorageHeart.GetHeart(Int32 i, Int32 j) in MagicStorage\Components\StorageHeart.cs:line 33
> >    at MagicStorage.StoragePlayer.GetStorageHeart() in MagicStorage\StoragePlayer.cs:line 190
> >    at MagicStorage.StorageGUI.GetHeart() in MagicStorage\StorageGUI.cs:line 335
> >    at MagicStorage.StorageGUI.RefreshItems() in MagicStorage\StorageGUI.cs:line 346
> >    at MagicStorage.Items.PortableAccess.OpenStorage(Player player) in MagicStorage\Items\PortableAccess.cs:line 110
> >    at MagicStorage.Items.PortableAccess.UseItem(Player player) in MagicStorage\Items\PortableAccess.cs:line 57
> >    at Terraria.ModLoader.ItemLoader.UseItem(Item item, Player player) in tModLoader\Terraria.ModLoader\ItemLoader.cs:line 766
> >    at Terraria.Player.ItemCheck(Int32 i) in tModLoader\Terraria\Player.cs:line 29618
> >    at Terraria.Player.ItemCheckWrapped(Int32 i) in tModLoader\Terraria\Player.cs:line 19140
> >    at DMD<Terraria.Player::Update>(Player this, Int32 i)
> >    at Terraria.Main.DoUpdate(GameTime gameTime) in tModLoader\Terraria\Main.cs:line 10588
> >    at Terraria.Main.Update(GameTime gameTime) in tModLoader\Terraria\Main.cs:line 10011
> >    at Microsoft.Xna.Framework.Game.Tick()
> >    at Microsoft.Xna.Framework.Game.HostIdle(Object sender, EventArgs e)
> >    at Microsoft.Xna.Framework.GameHost.OnIdle()
> >    at Microsoft.Xna.Framework.WindowsGameHost.RunOneFrame()
> >    at Microsoft.Xna.Framework.WindowsGameHost.ApplicationIdle(Object sender, EventArgs e)
> >    at System.Windows.Forms.Application.ThreadContext.System.Windows.Forms.UnsafeNativeMethods.IMsoComponent.FDoIdle(Int32 grfidlef)
> >    at System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr dwComponentID, Int32 reason, Int32 pvLoopData)
> >    at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)
> >    at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)
> >    at System.Windows.Forms.Application.Run(Form mainForm)
> >    at Microsoft.Xna.Framework.WindowsGameHost.Run()
> >    at Microsoft.Xna.Framework.Game.RunGame(Boolean useBlockingRun)
> >    at Terraria.Program.LaunchGame_() in tModLoader\Terraria\Program.cs:line 250
> >    at Terraria.Program.LaunchGame(String[] args, Boolean monoArgs) in tModLoader\Terraria\Program.cs:line 228
> >    at Terraria.WindowsLaunch.Main(String[] args) in tModLoader\Terraria\WindowsLaunch.cs:line 72
> > 
> > [13:40:09] [1/WARN] [tML]: Silently Caught Exception: 
> > System.NullReferenceException: Object reference not set to an instance of an object.
> >    at MagicStorage.InterfaceHelper.GetFullRectangle(UIElement element) in MagicStorage\InterfaceHelper.cs:line 71
> >    at MagicStorage.StorageGUI.UpdateDepositButton() in MagicStorage\StorageGUI.cs:line 367
> >    at MagicStorage.StorageGUI.Update(GameTime gameTime) in MagicStorage\StorageGUI.cs:line 261
> >    at MagicStorage.MagicStorage.PostUpdateInput() in MagicStorage.cs:line 326
> >    at Terraria.ModLoader.ModHooks.PostUpdateInput() in tModLoader\Terraria.ModLoader\ModHooks.cs:line 363
> >    at Terraria.Main.DoUpdate_HandleInput() in tModLoader\Terraria\Main.cs:line 10934
> >    at Terraria.Main.DoUpdate(GameTime gameTime) in tModLoader\Terraria\Main.cs:line 10307
> >    at Terraria.Main.Update(GameTime gameTime) in tModLoader\Terraria\Main.cs:line 10011
> >    at Microsoft.Xna.Framework.Game.Tick()
> >    at Microsoft.Xna.Framework.Game.HostIdle(Object sender, EventArgs e)
> >    at Microsoft.Xna.Framework.GameHost.OnIdle()
> >    at Microsoft.Xna.Framework.WindowsGameHost.RunOneFrame()
> >    at Microsoft.Xna.Framework.WindowsGameHost.ApplicationIdle(Object sender, EventArgs e)
> >    at System.Windows.Forms.Application.ThreadContext.System.Windows.Forms.UnsafeNativeMethods.IMsoComponent.FDoIdle(Int32 grfidlef)
> >    at System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr dwComponentID, Int32 reason, Int32 pvLoopData)
> >    at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)
> >    at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)
> >    at System.Windows.Forms.Application.Run(Form mainForm)
> >    at Microsoft.Xna.Framework.WindowsGameHost.Run()
> >    at Microsoft.Xna.Framework.Game.RunGame(Boolean useBlockingRun)
> >    at Terraria.Program.LaunchGame_() in tModLoader\Terraria\Program.cs:line 250
> >    at Terraria.Program.LaunchGame(String[] args, Boolean monoArgs) in tModLoader\Terraria\Program.cs:line 228
> >    at Terraria.WindowsLaunch.Main(String[] args) in tModLoader\Terraria\WindowsLaunch.cs:line 72
> > 
> > [13:40:09] [1/ERROR] [Terraria]: System.NullReferenceException: Object reference not set to an instance of an object.
> >    at MagicStorage.InterfaceHelper.GetFullRectangle(UIElement element) in MagicStorage\InterfaceHelper.cs:line 71
> >    at MagicStorage.StorageGUI.UpdateDepositButton() in MagicStorage\StorageGUI.cs:line 367
> >    at MagicStorage.StorageGUI.Update(GameTime gameTime) in MagicStorage\StorageGUI.cs:line 253
> >    at MagicStorage.MagicStorage.PostUpdateInput() in MagicStorage.cs:line 325
> >    at Terraria.ModLoader.ModHooks.PostUpdateInput() in tModLoader\Terraria.ModLoader\ModHooks.cs:line 362
> >    at Terraria.Main.DoUpdate_HandleInput() in tModLoader\Terraria\Main.cs:line 10933
> >    at Terraria.Main.DoUpdate(GameTime gameTime) in tModLoader\Terraria\Main.cs:line 10306
> >    at Terraria.Main.Update(GameTime gameTime) in tModLoader\Terraria\Main.cs:line 10010
> > [13:40:09] [1/WARN] [tML]: Silently Caught Exception: 
> > System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
> >    at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
> >    at MagicStorage.Components.StorageHeart.GetHeart(Int32 i, Int32 j) in MagicStorage\Components\StorageHeart.cs:line 33
> >    at MagicStorage.InterfaceHelper.DrawStorageGUI() in MagicStorage\InterfaceHelper.cs:line 48
> >    at Terraria.UI.LegacyGameInterfaceLayer.DrawSelf() in tModLoader\Terraria.UI\LegacyGameInterfaceLayer.cs:line 12
> >    at Terraria.UI.GameInterfaceLayer.Draw() in tModLoader\Terraria.UI\GameInterfaceLayer.cs:line 38
> >    at Terraria.Main.DrawInterface(GameTime gameTime) in tModLoader\Terraria\Main.cs:line 33316
> >    at Terraria.Main.DoDraw(GameTime gameTime) in tModLoader\Terraria\Main.cs:line 48519
> >    at Terraria.Main.Draw(GameTime gameTime) in tModLoader\Terraria\Main.cs:line 46942
> >    at Microsoft.Xna.Framework.Game.DrawFrame()
> >    at Microsoft.Xna.Framework.Game.Tick()
> >    at Microsoft.Xna.Framework.Game.HostIdle(Object sender, EventArgs e)
> >    at Microsoft.Xna.Framework.GameHost.OnIdle()
> >    at Microsoft.Xna.Framework.WindowsGameHost.RunOneFrame()
> >    at Microsoft.Xna.Framework.WindowsGameHost.ApplicationIdle(Object sender, EventArgs e)
> >    at System.Windows.Forms.Application.ThreadContext.System.Windows.Forms.UnsafeNativeMethods.IMsoComponent.FDoIdle(Int32 grfidlef)
> >    at System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr dwComponentID, Int32 reason, Int32 pvLoopData)
> >    at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)
> >    at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)
> >    at System.Windows.Forms.Application.Run(Form mainForm)
> >    at Microsoft.Xna.Framework.WindowsGameHost.Run()
> >    at Microsoft.Xna.Framework.Game.RunGame(Boolean useBlockingRun)
> >    at Terraria.Program.LaunchGame_() in tModLoader\Terraria\Program.cs:line 250
> >    at Terraria.Program.LaunchGame(String[] args, Boolean monoArgs) in tModLoader\Terraria\Program.cs:line 228
> >    at Terraria.WindowsLaunch.Main(String[] args) in tModLoader\Terraria\WindowsLaunch.cs:line 72
> > 
> > [13:40:09] [1/ERROR] [Terraria]: System.NullReferenceException: Object reference not set to an instance of an object.
> >    at MagicStorage.InterfaceHelper.GetFullRectangle(UIElement element) in MagicStorage\InterfaceHelper.cs:line 71
> >    at MagicStorage.StorageGUI.UpdateDepositButton() in MagicStorage\StorageGUI.cs:line 367
> >    at MagicStorage.StorageGUI.Update(GameTime gameTime) in MagicStorage\StorageGUI.cs:line 253
> >    at MagicStorage.MagicStorage.PostUpdateInput() in MagicStorage.cs:line 325
> >    at Terraria.ModLoader.ModHooks.PostUpdateInput() in tModLoader\Terraria.ModLoader\ModHooks.cs:line 362
> >    at Terraria.Main.DoUpdate_HandleInput() in tModLoader\Terraria\Main.cs:line 10933
> >    at Terraria.Main.DoUpdate(GameTime gameTime) in tModLoader\Terraria\Main.cs:line 10306
> >    at Terraria.Main.Update(GameTime gameTime) in tModLoader\Terraria\Main.cs:line 10010
> > [13:40:09] [1/ERROR] [Terraria]: System.NullReferenceException: Object reference not set to an instance of an object.
> >    at MagicStorage.InterfaceHelper.GetFullRectangle(UIElement element) in MagicStorage\InterfaceHelper.cs:line 71
> >    at MagicStorage.StorageGUI.UpdateDepositButton() in MagicStorage\StorageGUI.cs:line 367
> >    at MagicStorage.StorageGUI.Update(GameTime gameTime) in MagicStorage\StorageGUI.cs:line 253
> >    at MagicStorage.MagicStorage.PostUpdateInput() in MagicStorage.cs:line 325
> >    at Terraria.ModLoader.ModHooks.PostUpdateInput() in tModLoader\Terraria.ModLoader\ModHooks.cs:line 362
> >    at Terraria.Main.DoUpdate_HandleInput() in tModLoader\Terraria\Main.cs:line 10933
> >    at Terraria.Main.DoUpdate(GameTime gameTime) in tModLoader\Terraria\Main.cs:line 10306
> >    at Terraria.Main.Update(GameTime gameTime) in tModLoader\Terraria\Main.cs:line 10010
> > [13:40:09] [1/ERROR] [Terraria]: System.NullReferenceException: Object reference not set to an instance of an object.
> >    at MagicStorage.InterfaceHelper.GetFullRectangle(UIElement element) in MagicStorage\InterfaceHelper.cs:line 71
> >    at MagicStorage.StorageGUI.UpdateDepositButton() in MagicStorage\StorageGUI.cs:line 367
> >    at MagicStorage.StorageGUI.Update(GameTime gameTime) in MagicStorage\StorageGUI.cs:line 253
> >    at MagicStorage.MagicStorage.PostUpdateInput() in MagicStorage.cs:line 325
> >    at Terraria.ModLoader.ModHooks.PostUpdateInput() in tModLoader\Terraria.ModLoader\ModHooks.cs:line 362
> >    at Terraria.Main.DoUpdate_HandleInput() in tModLoader\Terraria\Main.cs:line 10933
> >    at Terraria.Main.DoUpdate(GameTime gameTime) in tModLoader\Terraria\Main.cs:line 10306
> >    at Terraria.Main.Update(GameTime gameTime) in tModLoader\Terraria\Main.cs:line 10010
> > [13:40:09] [1/ERROR] [Terraria]: System.NullReferenceException: Object reference not set to an instance of an object.
> >    at MagicStorage.InterfaceHelper.GetFullRectangle(UIElement element) in MagicStorage\InterfaceHelper.cs:line 71
> >    at MagicStorage.StorageGUI.UpdateDepositButton() in MagicStorage\StorageGUI.cs:line 367
> >    at MagicStorage.StorageGUI.Update(GameTime gameTime) in MagicStorage\StorageGUI.cs:line 253
> >    at MagicStorage.MagicStorage.PostUpdateInput() in MagicStorage.cs:line 325
> >    at Terraria.ModLoader.ModHooks.PostUpdateInput() in tModLoader\Terraria.ModLoader\ModHooks.cs:line 362
> >    at Terraria.Main.DoUpdate_HandleInput() in tModLoader\Terraria\Main.cs:line 10933
> >    at Terraria.Main.DoUpdate(GameTime gameTime) in tModLoader\Terraria\Main.cs:line 10306
> >    at Terraria.Main.Update(GameTime gameTime) in tModLoader\Terraria\Main.cs:line 10010
> > [13:40:09] [1/WARN] [tML]: Silently Caught Exception: 
> > System.InvalidOperationException: Begin cannot be called again until End has been successfully called.
> >    at Microsoft.Xna.Framework.Graphics.SpriteBatch.Begin(SpriteSortMode sortMode, BlendState blendState, SamplerState samplerState, DepthStencilState depthStencilState, RasterizerState rasterizerState, Effect effect, Matrix transformMatrix)
> >    at Terraria.Main.DoDraw(GameTime gameTime) in tModLoader\Terraria\Main.cs:line 47917
> >    at Terraria.Main.Draw(GameTime gameTime) in tModLoader\Terraria\Main.cs:line 46942
> >    at Microsoft.Xna.Framework.Game.DrawFrame()
> >    at Microsoft.Xna.Framework.Game.Tick()
> >    at Microsoft.Xna.Framework.Game.HostIdle(Object sender, EventArgs e)
> >    at Microsoft.Xna.Framework.GameHost.OnIdle()
> >    at Microsoft.Xna.Framework.WindowsGameHost.RunOneFrame()
> >    at Microsoft.Xna.Framework.WindowsGameHost.ApplicationIdle(Object sender, EventArgs e)
> >    at System.Windows.Forms.Application.ThreadContext.System.Windows.Forms.UnsafeNativeMethods.IMsoComponent.FDoIdle(Int32 grfidlef)
> >    at System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr dwComponentID, Int32 reason, Int32 pvLoopData)
> >    at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)
> >    at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)
> >    at System.Windows.Forms.Application.Run(Form mainForm)
> >    at Microsoft.Xna.Framework.WindowsGameHost.Run()
> >    at Microsoft.Xna.Framework.Game.RunGame(Boolean useBlockingRun)
> >    at Terraria.Program.LaunchGame_() in tModLoader\Terraria\Program.cs:line 250
> >    at Terraria.Program.LaunchGame(String[] args, Boolean monoArgs) in tModLoader\Terraria\Program.cs:line 228
> >    at Terraria.WindowsLaunch.Main(String[] args) in tModLoader\Terraria\WindowsLaunch.cs:line 72
> > 
> > [13:40:09] [1/ERROR] [Terraria]: System.InvalidOperationException: Begin cannot be called again until End has been successfully called.
> >    at Microsoft.Xna.Framework.Graphics.SpriteBatch.Begin(SpriteSortMode sortMode, BlendState blendState, SamplerState samplerState, DepthStencilState depthStencilState, RasterizerState rasterizerState, Effect effect, Matrix transformMatrix)
> >    at Terraria.Main.DoDraw(GameTime gameTime) in tModLoader\Terraria\Main.cs:line 47916
> >    at Terraria.Main.Draw(GameTime gameTime) in tModLoader\Terraria\Main.cs:line 46941
> > [13:40:10] [1/FATAL] [Terraria]: Main engine crash
> > System.InvalidOperationException: Begin cannot be called again until End has been successfully called.
> >    at Microsoft.Xna.Framework.Graphics.SpriteBatch.Begin(SpriteSortMode sortMode, BlendState blendState, SamplerState samplerState, DepthStencilState depthStencilState, RasterizerState rasterizerState, Effect effect, Matrix transformMatrix)
> >    at Terraria.Main.DoDraw(GameTime gameTime) in tModLoader\Terraria\Main.cs:line 47916
> >    at Terraria.Main.Draw(GameTime gameTime) in tModLoader\Terraria\Main.cs:line 46950
> >    at Microsoft.Xna.Framework.Game.DrawFrame()
> >    at Microsoft.Xna.Framework.Game.Tick()
> >    at Microsoft.Xna.Framework.Game.HostIdle(Object sender, EventArgs e)
> >    at Microsoft.Xna.Framework.GameHost.OnIdle()
> >    at Microsoft.Xna.Framework.WindowsGameHost.RunOneFrame()
> >    at Microsoft.Xna.Framework.WindowsGameHost.ApplicationIdle(Object sender, EventArgs e)
> >    at System.Windows.Forms.Application.ThreadContext.System.Windows.Forms.UnsafeNativeMethods.IMsoComponent.FDoIdle(Int32 grfidlef)
> >    at System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr dwComponentID, Int32 reason, Int32 pvLoopData)
> >    at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)
> >    at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)
> >    at System.Windows.Forms.Application.Run(Form mainForm)
> >    at Microsoft.Xna.Framework.WindowsGameHost.Run()
> >    at Microsoft.Xna.Framework.Game.RunGame(Boolean useBlockingRun)
> >    at Terraria.Program.LaunchGame_() in tModLoader\Terraria\Program.cs:line 250
> 

I'm not sure if it's some kind of incompatibility issue or not but I could send the mod list

**Comment by Redcom1988** [comment]
> [
>   "AlchemistNPCLite",
>   "AllTheWalls",
>   "AmmoboxPlus",
>   "AmmoCycle",
>   "AnglerPlusPlus",
>   "ApacchiisClassesMod",
>   "ArchaeaMod",
>   "ArgantiumReborn",
>   "AutoReroll",
>   "BameMod",
>   "BaseMod",
>   "BetterPaint",
>   "Bluemagic",
>   "BossChecklist",
>   "BossCursor",
>   "BothEvils",
>   "BrighterLight",
>   "BuilderEssentials",
>   "CellphoneIsWormhole",
>   "chadsfurni",
>   "ChampionMod",
>   "CheatSheet",
>   "CinematicMod",
>   "ClassEssences",
>   "DisableCorruptionSpread",
>   "DRGN",
>   "EldironsUtilities",
>   "ElementsAwoken",
>   "Emitters",
>   "EnemyMods",
>   "Events",
>   "FastBuilding",
>   "FasterPickaxes",
>   "FKBossHealthBar",
>   "GardenersMod",
>   "GlowMaskAPI",
>   "Hammerator",
>   "HamstarHelpers",
>   "HelpfulHotkeys",
>   "Intrinsics",
>   "InvTweaks",
>   "ItemsBuffs",
>   "Luiafk",
>   "MagicStorage",
>   "MechTransfer",
>   "Microstructures",
>   "MinionCrits",
>   "MountedMagicMirrors",
>   "NekoTweakMod",
>   "niceblocks",
>   "NMIP",
>   "NoFavoriteTooltips",
>   "NoMoreTombs",
>   "Origin",
>   "PickBlock",
>   "PiercingFix",
>   "PowerfulMagic",
>   "PreHMTeleportation",
>   "PseudoTweaks",
>   "RecipeBrowser",
>   "ReducedGrinding",
>   "RPGreforge",
>   "ShopExpander",
>   "ShorterRespawn",
>   "SmartDoors",
>   "SpiritMod",
>   "SteviesMod",
>   "StormDiversSuggestions",
>   "StructureHelper",
>   "SuperQuickRespawn",
>   "ThoriumMod",
>   "TimeAcceleration",
>   "TPUnchained",
>   "UnclutteredProjectiles",
>   "UnlimitedBuffs",
>   "VeinMiner",
>   "VipixToolBox",
>   "WingSlot",
>   "WMITF",
>   "WrenchMod"
> ]

This is the modlist.
