### ISSUE TITLE
crafting stopped working

### ISSUE THREAD

**Issue by joelthecannonmain** [blushiemagic/MagicStorage#108]
i got everything set up as usual. heart, crafting, access and some units then all the sudden crafting (despite having an anvil workbench among other crafting stations which arent modded in case your wondering) suddenly stopped showing recipes and on top of that everytime i went to search for something it would type all of my inputs up until that point (for example aaaadwsadaasa) hope this gets sorted soon. much love

**Comment by joelthecannonmain** [comment]
i have found a fix for this issue for anyone who has this same problem. in my games/terraria/modloader you can find the config.json and input profiles.json file deleting them both resets your settings so youll have to re-keybind everything but it fixes this crafting interface issue.

**Comment by bvers6** [comment]
Can confirm I've had this same issue and this fix worked today, it seemed that Universal Crafter was exacerbating this issue (too many recipes?) and the crafter interface was loading and reloading a lot hours before it broke

[12:17:10] [1/WARN] [tML]: Silently Caught Exception: 
System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
   at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   at MagicStorage.CraftingGUI.GetRecipe(Int32 slot, Int32& context) in MagicStorage\CraftingGUI.cs:line 496
   at MagicStorage.UISlotZone.DrawSelf(SpriteBatch spriteBatch) in MagicStorage\UISlotZone.cs:line 75
   at Terraria.UI.UIElement.Draw(SpriteBatch spriteBatch)
   at Terraria.UI.UIElement.DrawChildren(SpriteBatch spriteBatch)
   at Terraria.UI.UIElement.Draw(SpriteBatch spriteBatch)
   at MagicStorage.CraftingGUI.Draw(TEStorageHeart heart) in MagicStorage\CraftingGUI.cs:line 468
   at MagicStorage.InterfaceHelper.DrawStorageGUI() in MagicStorage\InterfaceHelper.cs:line 55
   at Terraria.UI.GameInterfaceLayer.Draw()
   at DMD<Terraria.Main::DrawInterface>(Main , GameTime )
   at SpiritMod.SpiritDetours.DrawParticles(orig_DrawInterface orig, Main self, GameTime gameTime) in SpiritMod\SpiritDetours.cs:line 85
   at DMD<DMD<Hook<Terraria.Main::DrawInterface>?54657003>?41022375::Hook<Terraria.Main::DrawInterface>?54657003>(Main , GameTime )
   at DMD<Terraria.Main::DoDraw>(Main , GameTime )
   at Terraria.Main.Draw(GameTime gameTime)
   at Microsoft.Xna.Framework.Game.Tick()
   at Microsoft.Xna.Framework.SDL2_FNAPlatform.RunLoop(Game game)
   at Microsoft.Xna.Framework.Game.Run()
   at Terraria.Program.LaunchGame_()
   at Terraria.Program.LaunchGame(String[] args, Boolean monoArgs)
   at Terraria.FNALaunch.Main(String[] args)
[2021-05-31-4.zip](https://github.com/blushiemagic/MagicStorage/files/6567452/2021-05-31-4.zip)

**Comment by absoluteAquarian** [comment]
The following message has been copy/pasted to all issues older than 3 months.

In order to clean up how the project looks, I'll be closing all old issues.  If you believe that this issue is still relevant, please make a new issue that references this issue in its message.

**Comment by joelthecannonmain** [comment]
Hey. So not sure how I’m getting these emails. But I am a COMPLETE
stranger. And while I absolutely love terraria and the modding community
for it, You should probably go about finding the ACTUAL guy you guys are
trying to email.

Best of luck.

- some guy called Joel.
