### ISSUE TITLE
Error while loading MagicStorage

### ISSUE THREAD

**Issue by masTerTaTerr** [blushiemagic/MagicStorage#130]
Using MagicStorage on tmodloader 1.4.2.3   As of today, I get an error when I start tmodloader up and it won't load MagicStorage and 2 other mods I had enabled, but does load others.  "MagicStorage.Items.Locator has old Load/Save callbacks but not new LoadData/SaveData ones, not loading the mod to avoid wiping mod data"

**Comment by alder-nighthawk** [comment]
Can confirm.  This issue was also present with the Clicker Class mod but was resolved with the Clicker Class being recently updated.

Full error log in the spoiler.

<details>
        <summary>Logs</summary>
         System.Exception: MagicStorage.Items.Locator has old Load/Save callbacks but not new LoadData/SaveData ones, not loading the mod to avoid wiping mod data
   at Terraria.ModLoader.ModItem.Register() in tModLoader\Terraria\ModLoader\ModItem.cs:line 55
   at Terraria.ModLoader.ModType.Terraria.ModLoader.ILoadable.Load(Mod mod) in tModLoader\Terraria\ModLoader\ModType.cs:line 26
   at Terraria.ModLoader.Mod.AddContent(ILoadable instance) in tModLoader\Terraria\ModLoader\Mod.cs:line 140
   at Terraria.ModLoader.Mod.Autoload() in tModLoader\Terraria\ModLoader\Mod.Internals.cs:line 76
   at Terraria.ModLoader.ModContent.<>c.<Load>b__41_0(Mod mod) in tModLoader\Terraria\ModLoader\ModContent.cs:line 302
   at Terraria.ModLoader.ModContent.LoadModContent(CancellationToken token, Action`1 loadAction) in tModLoader\Terraria\ModLoader\ModContent.cs:line 358
   at Terraria.ModLoader.ModContent.Load(CancellationToken token) in tModLoader\Terraria\ModLoader\ModContent.cs:line 297
   at Terraria.ModLoader.ModLoader.Load(CancellationToken token) in tModLoader\Terraria\ModLoader\ModLoader.cs:line 130
    </details>

**Comment by ExterminatorX99** [comment]
Issue is fixed in the upcoming update

**Comment by absoluteAquarian** [comment]
The following message has been copy/pasted to all issues older than 3 months.

In order to clean up how the project looks, I'll be closing all old issues.  If you believe that this issue is still relevant, please make a new issue that references this issue in its message.
