### ISSUE TITLE
[1.4 alpha] Crafting interface bug

### ISSUE THREAD

**Issue by gosvoh** [blushiemagic/MagicStorage#137]
Got this exception, when tried to pull out crafting stations from the crafting interface
```c#
System.MissingMethodException: Method not found: 'Void Terraria.Player.QuickSpawnClonedItem(Terraria.Item, Int32)'.
   at MagicStorage.CraftingGUI.HoverStation(Int32 slot, Int32& hoverSlot)
   at MagicStorage.UI.UISlotZone.Update(GameTime gameTime) in MagicStorage\UI\UISlotZone.cs:line 57
   at Terraria.UI.UIElement.Update(GameTime gameTime) in tModLoader\Terraria\UI\UIElement.cs:line 203
   at MagicStorage.CraftingGUI.Update(GameTime gameTime) in MagicStorage\CraftingGUI.cs:line 444
   at Terraria.ModLoader.SystemLoader.PostUpdateInput() in tModLoader\Terraria\ModLoader\SystemLoader.cs:line 270
   at Terraria.Main.DoUpdate_HandleInput() in tModLoader\Terraria\Main.cs:line 13710
   at Terraria.Main.DoUpdate(GameTime& gameTime) in tModLoader\Terraria\Main.cs:line 12859
   at DMD<Terraria.Main::Update>(Main this, GameTime gameTime)
   at TomatoLib.Core.Threading.GLCallLocker.CallActionsOnMainThread(orig_Update orig, Main self, GameTime gameTime)
   at Microsoft.Xna.Framework.Game.Tick() in D:\a\tModLoader\tModLoader\FNA\src\Game.cs:line 485
   at Microsoft.Xna.Framework.Game.RunLoop() in D:\a\tModLoader\tModLoader\FNA\src\Game.cs:line 880
   at Microsoft.Xna.Framework.Game.Run() in D:\a\tModLoader\tModLoader\FNA\src\Game.cs:line 415
   at Terraria.Program.LaunchGame_(Boolean isServer)
   at Terraria.Program.LaunchGame(String[] args, Boolean monoArgs)
   at MonoLaunch.Main(String[] args)
```
and the same one when tried to craft items
```c#
System.MissingMethodException: Method not found: 'Void Terraria.Player.QuickSpawnClonedItem(Terraria.Item, Int32)'.
   at MagicStorage.CraftingGUI.TryCraft()
   at MagicStorage.CraftingGUI.UpdateCraftButton() in MagicStorage\CraftingGUI.cs:line 815
   at MagicStorage.CraftingGUI.Update(GameTime gameTime) in MagicStorage\CraftingGUI.cs:line 448
   at Terraria.ModLoader.SystemLoader.PostUpdateInput() in tModLoader\Terraria\ModLoader\SystemLoader.cs:line 270
   ...
```

**Comment by ExterminatorX99** [comment]
Known issue. You'll have to wait for the mod to be updated

**Comment by namenth** [comment]
Just to add, I am getting the same bug. It gets thrown when I hover over the crafting stations inside the crafting interface.

**Comment by namenth** [comment]
Seems like the most recent manual update from the discord resolves this issue.

**Comment by absoluteAquarian** [comment]
Issue has been resolved by manual installs from the past and recent update in the workshop.
