### ISSUE TITLE
[Multiplayer] Receiving tile data: completed stuck

### ISSUE THREAD

**Issue by Kasumaca** [blushiemagic/MagicStorage#158]
3 of us are going to do a modded playthrough, at first everything was fine, 2 days later I was stuck at "Receiving tile data: complete" for 2 days and tried disabling all mods and enabling them one by one, until magic storage turned on the error occurred, and only me and the other 2 are fine

**Comment by Kasumaca** [comment]
[12:05:30] [1/WARN] [tML]: Silently Caught Exception: 
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at DMD<Terraria.MessageBuffer::GetData>(MessageBuffer , Int32 , Int32 , Int32& )
   at MagicStorage.Edits.Detours.Vanilla.MessageBuffer_GetData(orig_GetData orig, MessageBuffer self, Int32 start, Int32 length, Int32& messageType) in MagicStorage\Edits\Detours\Vanilla.NetMessage.cs:line 164
   at DMD<DMD<Hook<Terraria.MessageBuffer::GetData>?16690800>?13234184::Hook<Terraria.MessageBuffer::GetData>?16690800>(MessageBuffer , Int32 , Int32 , Int32& )
   at Terraria.NetMessage.CheckBytes(Int32 bufferIndex)
   at System.Threading.Tasks.Task.Execute()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
   at System.Threading.Tasks.Task.ExecuteEntry(Boolean bPreventDoubleExecution)
   at System.Threading.Tasks.ThreadPoolTaskScheduler.TryExecuteTaskInline(Task task, Boolean taskWasPreviouslyQueued)
   at System.Threading.Tasks.TaskScheduler.TryRunInline(Task task, Boolean taskWasPreviouslyQueued)
   at System.Threading.Tasks.Task.InternalRunSynchronously(TaskScheduler scheduler, Boolean waitForCompletion)
   at Terraria.Netplay.OnUpdate()
   at Terraria.Main.DoUpdate(GameTime gameTime)
   at Terraria.Main.Update(GameTime gameTime)
   at Microsoft.Xna.Framework.Game.Tick()
   at Microsoft.Xna.Framework.SDL2_FNAPlatform.RunLoop(Game game)
   at Microsoft.Xna.Framework.Game.Run()
   at Terraria.Program.LaunchGame_()
   at Terraria.Program.LaunchGame(String[] args, Boolean monoArgs)
   at Terraria.FNALaunch.Main(String[] args)

**Comment by Haphaistos2333** [comment]
Same issue here. We are playing magic storage with Calamity Mod, and we got similar backtrace and IndexOutOfRange exceptions.

**Comment by ExterminatorX99** [comment]
Does this still happen if you disable Magic Storage?

**Comment by absoluteAquarian** [comment]
The following message has been copy/pasted to all issues older than 3 months.

In order to clean up how the project looks, I'll be closing all old issues.  If you believe that this issue is still relevant, please make a new issue that references this issue in its message.
