### ISSUE TITLE
[Crash] `ArgumentOutOfRangeException` at `MagicStorage.Components.TEStorageUnit.SaveData`

### ISSUE THREAD

**Issue by Phoupraw** [blushiemagic/MagicStorage#224]
TML crashed at the moment I used crafting interface to craft. The following is the latest flash, and then tml lagged and crashed.
![崩溃前画面2](https://user-images.githubusercontent.com/50520903/211568621-16e96372-0204-434e-ba9e-f6d1db0e104b.png)
[logs.zip](https://github.com/blushiemagic/MagicStorage/files/10383310/logs.zip)
> [21:42:03.362] [.NET ThreadPool Worker/WARN] [tML]: 静默捕获异常: 
System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
   at System.Linq.Enumerable.SelectListIterator`2.ToList()
   at MagicStorage.Components.TEStorageUnit.SaveData(TagCompound tag) in MagicStorage\Components\TEStorageUnit.cs:line 407
   at Terraria.ModLoader.IO.TileIO.SaveTileEntities() in tModLoader\Terraria\ModLoader\IO\TileIO_TEs.cs:line 21
   at Terraria.ModLoader.IO.WorldIO.Save(String path, Boolean isCloudSave) in tModLoader\Terraria\ModLoader\IO\WorldIO.cs:line 25
   at Terraria.IO.WorldFile.InternalSaveWorld(Boolean useCloudSaving, Boolean resetTime) in tModLoader\Terraria\IO\WorldFile.cs:line 564
   at Terraria.Utilities.FileUtilities.ProtectedInvoke(Action action) in tModLoader\Terraria\Utilities\FileUtilities.cs:line 170
   at Terraria.IO.WorldFile.SaveWorld(Boolean useCloudSaving, Boolean resetTime) in tModLoader\Terraria\IO\WorldFile.cs:line 499
   at Terraria.IO.WorldFile.SaveWorld() in tModLoader\Terraria\IO\WorldFile.cs:line 476
   at System.Threading.QueueUserWorkItemCallback.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()

**Comment by absoluteAquarian** [comment]
The following message has been copy/pasted to all issues older than 3 months.

In order to clean up how the project looks, I'll be closing all old issues.  If you believe that this issue is still relevant, please make a new issue that references this issue in its message.
