### ISSUE TITLE
MagicStorage Multiplayer and Crafting Access Problem

### ISSUE THREAD

**Issue by dexter3884** [blushiemagic/MagicStorage#48]
```
Silently Caught Exception: Collection was modified; enumeration operation may not execute.   at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)   at Terraria.ModLoader.ModCompile.<>c.<ActivateExceptionReporting>b__15_0(Object sender, FirstChanceExceptionEventArgs exceptionArgs)
   at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.KeyCollection.Enumerator.MoveNext()
   at MagicStorage.CraftingGUI.IsAvailable(Recipe recipe)
   at MagicStorage.CraftingGUI.<RefreshRecipes>b__5(Recipe recipe)
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at System.Collections.Generic.List`1.InsertRange(Int32 index, IEnumerable`1 collection)
   at MagicStorage.CraftingGUI.RefreshRecipes()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
```

Crafting recipes are visible on host side but not for anyone else. This error specifically occurs when someone that cannot see the recipes looks up an item in the search-bar. Supposedly this error was supposed to be resolved with issue #20 but we are still having problems.

The following mods are being used alongside MagicStorage:
- Thorium Mod
- Reduced Grinding
- Boss Checklist

**Comment by HikloLime** [comment]
I have the exact same issue. Holding right click over the crafting terminal and any storage component will freeze the character mid air and vanity hats will become invisible.
It might have something to do with the fact I'm on linux.

**Comment by absoluteAquarian** [comment]
The following message has been copy/pasted to all issues older than 3 months.

In order to clean up how the project looks, I'll be closing all old issues.  If you believe that this issue is still relevant, please make a new issue that references this issue in its message.
