### ISSUE TITLE
Crafting Interface GUI disappears on cursor contact

### ISSUE THREAD

**Issue by billyma6** [blushiemagic/MagicStorage#57]
Hi, so I just installed MS on my brand new world, and when I click on the storage crafting interface, it repeatedly gives me this error:

Code:
System.NullReferenceException: Object reference not set to an instance of an object.
at MagicStorage.InterfaceHelper.HideItemIconCache()
at MagicStorage.CraftingGUI.Draw(TEStorageHeart heart)
I can still interact with the interface, however whenever my mouse touches the GUI the interface disappears and I hear repeated whirring sounds of text appearing. Anyone know what’s going on?

My game has also crashed, and when rebooted, every world refuses to open, even with brand new characters.

Terraria 1.3.5.2
tModLoader 0.10.1.5

VeinMiner
Calamity
Thorium
Infinity
Wireless
Yet Another Boss Health Bar
What Mod is This From
Dual Wielding
Solutions
Max Stacks Plus
JoostMod
Cheat Sheet
AlchemistNPC
Fargo’s Mutant Mod
imkSushi’s Mod

https://forums.terraria.org/index.php?attachments/runtime-error-txt.206028/
https://forums.terraria.org/index.php?attachments/logs-txt.206029/
https://forums.terraria.org/index.php?attachments/client-crashlog-txt.206030/
https://forums.terraria.org/index.php?attachments/runtime-error-txt.206034/

**Comment by absoluteAquarian** [comment]
The following message has been copy/pasted to all issues older than 3 months.

In order to clean up how the project looks, I'll be closing all old issues.  If you believe that this issue is still relevant, please make a new issue that references this issue in its message.
