### ISSUE TITLE
Trying to open access point does nothing.

### ISSUE THREAD

**Issue by RacerDelux** [blushiemagic/MagicStorage#6]
On our server currently, when trying to open one of the access points (either the storage heart or a remote access), instead of opening, it looks like it all of your cosmetic items are hidden for the duration of the right click.
Occasionally I crash when trying to open it.
https://i.gyazo.com/d6d84089586ba3a69e418f304cc70396.png

> The given key was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at MagicStorage.Components.TEStorageHeart.<GetStorageUnits>b__0(Point16 remoteAccess)
   at System.Linq.Enumerable.<SelectManyIterator>d__16`2.MoveNext()
   at System.Linq.Enumerable.<ConcatIterator>d__58`1.MoveNext()
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.<SelectManyIterator>d__16`2.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at MagicStorage.Sorting.ItemSorter.SortAndFilter(IEnumerable`1 items, SortMode sortMode, FilterMode filterMode, String modFilter, String nameFilter)
   at MagicStorage.StorageGUI.RefreshItems()
   at MagicStorage.StorageGUI.UpdateItemSlots()
   at MagicStorage.StorageGUI.Update(GameTime gameTime)
   at MagicStorage.MagicStorage.PostUpdateInput()
   at Terraria.ModLoader.ModHooks.PostUpdateInput()
   at Terraria.Main.DoUpdate(GameTime gameTime)
   at Terraria.Main.Update(GameTime gameTime)
----------------------------------------------------------------
Wanted to give some further information. When I MOVED the heart to a different spot, it started working no crash:
https://i.gyazo.com/991ac95f9a1bb1a3ae6df4284359bfd2.png
The original location:
https://i.gyazo.com/cfd06170f3de66cdacb8efcf3208820a.png

**Comment by bluemagic123** [comment]
Does this bug still happen with the new updated released today?
