### ISSUE TITLE
My Magic Storage reduces from 1920 to 320 in MP and we can't access the Crafting component!

### ISSUE THREAD

**Issue by ImAsiann** [blushiemagic/MagicStorage#68]
It started yesterday, my friends started to not be able to use the Crafting component, then i tried to reboot the server, i tried to remove and add again the mod. Nothing worked, and in Single Player i can play it normally. The last message from the log is this: Silently Caught Exception: Object reference not set to an instance of an object.   at MagicStorage.CraftingGUI.AnalyzeIngredients()   at Terraria.ModLoader.ModCompile.<>c.<ActivateExceptionReporting>b__15_0(Object sender, FirstChanceExceptionEventArgs exceptionArgs)
   at MagicStorage.CraftingGUI.AnalyzeIngredients()
   at MagicStorage.CraftingGUI.RefreshItems()
   at MagicStorage.StorageGUI.RefreshItems()
   at MagicStorage.Components.StorageAccess.RightClick(Int32 i, Int32 j)
   at Terraria.ModLoader.TileLoader.RightClick(Int32 i, Int32 j)
   at Terraria.Player.TileInteractionsUse(Int32 myX, Int32 myY)
   at Terraria.Player.TileInteractionsCheck(Int32 myX, Int32 myY)
   at Terraria.Player.LookForTileInteractions()
   at Terraria.Player.Update(Int32 i)
   at Terraria.Main.DoUpdate(GameTime gameTime)
   at Terraria.Main.Update(GameTime gameTime)
   at Microsoft.Xna.Framework.Game.Tick()
   at Microsoft.Xna.Framework.Game.HostIdle(Object sender, EventArgs e)
   at Microsoft.Xna.Framework.GameHost.OnIdle()
   at Microsoft.Xna.Framework.WindowsGameHost.RunOneFrame()
   at Microsoft.Xna.Framework.WindowsGameHost.ApplicationIdle(Object sender, EventArgs e)
   at System.Windows.Forms.Application.ThreadContext.System.Windows.Forms.UnsafeNativeMethods.IMsoComponent.FDoIdle(Int32 grfidlef)
   at System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr dwComponentID, Int32 reason, Int32 pvLoopData)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.Run(Form mainForm)
   at Microsoft.Xna.Framework.WindowsGameHost.Run()
   at Microsoft.Xna.Framework.Game.RunGame(Boolean useBlockingRun)
   at Terraria.Program.LaunchGame(String[] args, Boolean monoArgs)
   at Terraria.WindowsLaunch.Main(String[] args)

Can anybody help me to solve it? We really liked the mod, it is very helpfull, it is a shame if we can't get it fix

**Comment by Ekagrah** [comment]
We had a similar thing happen yesterday, storage reduced to show much less capacity. Friend locked up and did Alt+F4. I played fine for a bit then restarted since he couldn’t get in, now we cannot start in multiplayer, but I can do solo without issue. Always hangs at “Recieving tile data 100%”.

Additionally, we had Spirit mod spawn ore over our storage nodes...right-clicking a storage node near the ore or trying to use pick on empty node or the ore caused a crash. Dunno if the two are related. Have had to move 1500 items twice now...

**Comment by absoluteAquarian** [comment]
The following message has been copy/pasted to all issues older than 3 months.

In order to clean up how the project looks, I'll be closing all old issues.  If you believe that this issue is still relevant, please make a new issue that references this issue in its message.
