### ISSUE TITLE
Remote Storage Access is not connectable

### ISSUE THREAD

**Issue by Heavy-Systems** [blushiemagic/MagicStorage#81]
If there is already a storage heart placed down, it is NOT possible to connect a Remote Storage Access in any way to the Storage Heart. The Remote Storage Access can only be placed with a minimum of one block away from any of the MagicStorage blocks.

If there is no storage heart placed down, placing down the Remote Storage Access is possible. BUT: After placing the Remote Storage Access, placing down a Storage Heart is not possible (see above).

Here is the content of the log when trying to place down a Remote Storage Access:

Silently Caught Exception: Object reference not set to an instance of an object.   at Terraria.TileObject.CanPlace(Int32 x, Int32 y, Int32 type, Int32 style, Int32 dir, TileObject& objectData, Boolean onlyCheck, Boolean checkStay)   at Terraria.ModLoader.ModCompile.<>c.<ActivateExceptionReporting>b__15_0(Object sender, FirstChanceExceptionEventArgs exceptionArgs)
   at Terraria.TileObject.CanPlace(Int32 x, Int32 y, Int32 type, Int32 style, Int32 dir, TileObject& objectData, Boolean onlyCheck, Boolean checkStay)
   at Terraria.Player.PlaceThing()
   at Terraria.Player.ItemCheck(Int32 i)
   at DMD<DMD<Trampoline:Native<0000000059350040>?31810815>?36149499::Trampoline:Native<0000000059350040>?31810815>(Player , Int32 )
   at TerrariaOverhaul.OverhaulPlayer.Player_ItemCheck(Player player, Int32 id) in D:\Steam\steamapps\common\Terraria\ModLoader\Mod Sources\TerrariaOverhaul\Systems\Features\Repair\RepairSystem.cs:line 80
   at Terraria.Player.ItemCheckWrapped(Int32 i)
   at Terraria.Player.Update(Int32 i)
   at Terraria.Main.DoUpdate(GameTime gameTime)
   at Terraria.Main.Update(GameTime gameTime)
   at Microsoft.Xna.Framework.Game.Tick()
   at Microsoft.Xna.Framework.Game.HostIdle(Object sender, EventArgs e)
   at Microsoft.Xna.Framework.GameHost.OnIdle()
   at Microsoft.Xna.Framework.WindowsGameHost.RunOneFrame()
   at Microsoft.Xna.Framework.WindowsGameHost.ApplicationIdle(Object sender, EventArgs e)
   at System.Windows.Forms.Application.ThreadContext.System.Windows.Forms.UnsafeNativeMethods.IMsoComponent.FDoIdle(Int32 grfidlef)
   at System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr dwComponentID, Int32 reason, Int32 pvLoopData)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.Run(Form mainForm)
   at Microsoft.Xna.Framework.WindowsGameHost.Run()
   at Microsoft.Xna.Framework.Game.RunGame(Boolean useBlockingRun)
   at Terraria.Program.LaunchGame(String[] args, Boolean monoArgs)
   at Terraria.WindowsLaunch.Main(String[] args)

This is the case with and without any other mods.

**Comment by blushiemagic** [comment]
This is intentional; it's the same as how you can't connect two storage hearts to each other. A remote access is meant to be connected remotely, not directly.
